export const sports = [
  { id: "football", label: "Football", icon: "⚽", count: "240+" },
  { id: "cricket", label: "Cricket", icon: "🏏", count: "85+" },
  { id: "badminton", label: "Badminton", icon: "🏸", count: "320+" },
  { id: "tennis", label: "Tennis", icon: "🎾", count: "160+" },
  { id: "basketball", label: "Basketball", icon: "🏀", count: "95+" },
  { id: "volleyball", label: "Volleyball", icon: "🏐", count: "72+" },
  { id: "swimming", label: "Swimming", icon: "🏊", count: "48+" },
  { id: "pickleball", label: "Pickleball", icon: "🏓", count: "38+" },
  { id: "squash", label: "Squash", icon: "🟡", count: "64+" },
  { id: "padel", label: "Padel", icon: "🎯", count: "28+" },
];

export const venues = [
  {
    id: 1,
    name: "Elite Football Ground",
    location: "Whitefield, Bangalore",
    address: "No. 14, Whitefield Main Rd, Whitefield, Bangalore – 560066",
    sports: ["Football"],
    sportIcon: "⚽",
    rating: 4.9,
    reviews: 284,
    pricePerHour: 800,
    distance: "1.2 km",
    available: true,
    badge: "Top Rated",
    type: "Outdoor",
    images: [
      "https://images.unsplash.com/photo-1513609698234-16d36e4b7a65?w=960&h=560&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1650327987377-90bf6c9789fd?w=960&h=560&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1520470082789-e347ad8b1944?w=960&h=560&fit=crop&auto=format",
    ],
    amenities: ["Floodlights", "Parking", "Changing Room", "Drinking Water", "WiFi", "First Aid"],
    description:
      "A premium full-size football ground with FIFA-approved synthetic turf, professional flood lighting, and state-of-the-art facilities. Perfect for 5-a-side, 7-a-side, and 11-a-side matches. The synthetic turf is replaced annually to ensure a consistent, high-quality playing surface.",
    rules: [
      "Footwear: Studs or flats only — no spikes",
      "No alcohol or smoking on premises",
      "Maximum 22 players per booking",
      "Arrive at least 10 minutes before your slot",
    ],
    reviewList: [
      { name: "Kiran R.", avatar: "KR", rating: 5, date: "Jul 12, 2025", comment: "Best ground in Whitefield. Turf quality is excellent and floodlights are very bright." },
      { name: "Aditya M.", avatar: "AM", rating: 5, date: "Jul 8, 2025", comment: "Loved playing here. Changing rooms are clean and staff is helpful." },
      { name: "Siddharth P.", avatar: "SP", rating: 4, date: "Jun 29, 2025", comment: "Great facility. Parking can get tight on weekends but worth it." },
    ],
  },
  {
    id: 2,
    name: "SkyLine Tennis Club",
    location: "Koramangala, Bangalore",
    address: "80 Feet Rd, 4th Block, Koramangala, Bangalore – 560034",
    sports: ["Tennis"],
    sportIcon: "🎾",
    rating: 4.8,
    reviews: 192,
    pricePerHour: 600,
    distance: "2.4 km",
    available: true,
    badge: "Trending",
    type: "Indoor",
    images: [
      "https://images.unsplash.com/photo-1761404984667-16d6c9158c59?w=960&h=560&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1766675122854-28fc70f50132?w=960&h=560&fit=crop&auto=format",
    ],
    amenities: ["3 Courts", "Pro Shop", "Coaching Available", "Parking", "Café", "Locker Room"],
    description:
      "SkyLine Tennis Club offers 3 premium hard courts with a world-class acrylic surface. Whether you are a beginner or a seasoned player, our courts deliver an exceptional experience. Our certified coaches offer sessions on request.",
    rules: [
      "Tennis shoes mandatory — no running shoes on courts",
      "Maximum 4 players per court",
      "Racket rental available at reception for ₹100",
    ],
    reviewList: [
      { name: "Priya S.", avatar: "PS", rating: 5, date: "Jul 15, 2025", comment: "Courts are amazing. The café nearby is a great bonus after the game." },
      { name: "Rohit G.", avatar: "RG", rating: 4, date: "Jul 1, 2025", comment: "Good court quality and friendly staff. Will definitely return." },
    ],
  },
  {
    id: 3,
    name: "BlueShuttle Badminton",
    location: "Indiranagar, Bangalore",
    address: "100 Feet Rd, HAL 2nd Stage, Indiranagar, Bangalore – 560038",
    sports: ["Badminton"],
    sportIcon: "🏸",
    rating: 4.7,
    reviews: 438,
    pricePerHour: 350,
    distance: "3.1 km",
    available: true,
    badge: "Popular",
    type: "Indoor",
    images: [
      "https://images.unsplash.com/photo-1775993167393-f2add1f8eec2?w=960&h=560&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1718452739586-5b467f1f109b?w=960&h=560&fit=crop&auto=format",
    ],
    amenities: ["8 Courts", "AC", "Equipment Rental", "Locker Room", "Coaching", "Canteen"],
    description:
      "The largest indoor badminton facility in Indiranagar with 8 professional PU courts, full air-conditioning, and certified coaches on standby. Open 6 AM to 12 midnight daily, 365 days a year.",
    rules: [
      "Non-marking shoes only — strictly enforced",
      "Shuttles available for purchase at reception (₹120/tube)",
      "No outside food or beverages",
    ],
    reviewList: [
      { name: "Anjali K.", avatar: "AK", rating: 5, date: "Jul 17, 2025", comment: "8 courts and always slots available. Best badminton center in Bangalore." },
      { name: "Ramesh V.", avatar: "RV", rating: 5, date: "Jul 10, 2025", comment: "Courts are very well maintained. AC keeps the temperature perfect." },
      { name: "Deepa N.", avatar: "DN", rating: 4, date: "Jun 25, 2025", comment: "Great place. Could use more parking but courts are top-notch." },
    ],
  },
  {
    id: 4,
    name: "Urban Hoops Arena",
    location: "HSR Layout, Bangalore",
    address: "Sector 2, HSR Layout, Bangalore – 560102",
    sports: ["Basketball"],
    sportIcon: "🏀",
    rating: 4.6,
    reviews: 156,
    pricePerHour: 500,
    distance: "4.8 km",
    available: false,
    badge: null,
    type: "Outdoor",
    images: [
      "https://images.unsplash.com/photo-1502014822147-1aedfb0676e0?w=960&h=560&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1590227632180-80a3bf110871?w=960&h=560&fit=crop&auto=format",
    ],
    amenities: ["Full Court", "Flood Lights", "Seating Area", "Drinking Water", "Parking"],
    description:
      "Urban Hoops Arena features a professional-grade full basketball court with premium wooden flooring and NBA-height adjustable hoops. Perfect for pickup games, practice sessions, and small tournaments.",
    rules: [
      "Basketball shoes only — no regular sneakers",
      "Maximum 10 players per booking",
      "No dunking on practice baskets",
    ],
    reviewList: [
      { name: "Varun T.", avatar: "VT", rating: 5, date: "Jul 14, 2025", comment: "Floor quality is superb. Feels like a real arena." },
      { name: "Nisha P.", avatar: "NP", rating: 4, date: "Jul 3, 2025", comment: "Great court and good value for money. Loved the lighting at night." },
    ],
  },
];

export type Venue = (typeof venues)[0];
